'use strict';

/**
 * Image service — pre-signed S3 upload URLs for product pictures.
 * The bucket stays private: uploads use short-lived PUT URLs, reads use
 * pre-signed GET URLs generated by the products service.
 *
 *   const images = createImagesService({ s3, bucket, signUrl });
 */

const { randomUUID } = require('node:crypto');
const { PutObjectCommand } = require('@aws-sdk/client-s3');
const { HttpError } = require('../common');

const UPLOAD_TTL = 300; // seconds

const ALLOWED_TYPES = {
    'image/png': 'png',
    'image/jpeg': 'jpg',
    'image/webp': 'webp',
    'image/gif': 'gif',
};

function createImagesService({ s3, bucket, signUrl, uploadTtl = UPLOAD_TTL }) {
    /**
     * @param {{fileName?: string, contentType?: string}} body
     * @returns {Promise<{uploadUrl: string, key: string, expiresIn: number}>}
     */
    async function createUploadUrl(body) {
        const contentType = String(body?.contentType ?? '');
        const fileName = String(body?.fileName ?? '');

        const ext = ALLOWED_TYPES[contentType];
        if (!ext) throw new HttpError(415, 'Unsupported image type. Use PNG, JPEG, WEBP or GIF.');

        const safeName =
            fileName.toLowerCase().replace(/[^a-z0-9._-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) ||
            `image.${ext}`;

        const key = `products/${randomUUID()}-${safeName}`;
        const uploadUrl = await signUrl(
            s3,
            new PutObjectCommand({ Bucket: bucket, Key: key, ContentType: contentType }),
            { expiresIn: uploadTtl },
        );

        return { uploadUrl, key, expiresIn: uploadTtl };
    }

    return { createUploadUrl, allowedTypes: Object.keys(ALLOWED_TYPES) };
}

module.exports = { createImagesService, UPLOAD_TTL, ALLOWED_TYPES };
